### ISSUE TITLE
Different default models for B->K*ll@LargeRecoil and B->K*ll@LowRecoil

### ISSUE THREAD

**Issue by cBobeth** [eos/eos#131]
The default models used by B->K^*ll@LargeRecoil and B->K^*ll@LowRecoil are not consistent:

B->K^*ll@LargeRecoil uses 'model->WilsonScan'
B->K^*ll@LowRecoil uses 'model->SM'

We should agree on some common default throughout EOS. Maybe 'model->SM'?!

**Comment by dvandyk** [comment]
@cBobeth I would argue that this is dependent on the transitions:
 - for *b->sll* the option ```model=WilsonScan``` is benefitial, since it speeds up evaluation when you do not require the running from the high scale to the low scale; i.e., when you keep the SM parameters at their defaults.
 - for `b->clnu* the options ```model=WilsonScan``` and ```model=CKMScan``` kind of compete; I am slightly in favour of using ```model=CKMScan```.

@gubernari After your talk at DESY, could you provide us here with an overview of the various default values for the option ```model``` used in the code?

**Comment by dvandyk** [comment]
@mreboud is this solved by your recent PR?

**Comment by mreboud** [comment]
Yes, all is WilsonScan now.
