### ISSUE TITLE
Choose a name between D^*_s and D_s^*

### ISSUE THREAD

**Issue by gubernari** [eos/eos#176]
In some part of the code it is adopted the name `D_s^*`, in other parts `D^*_s.` I suggest we should decide between one of these two names and adapt the code consistently.

**Comment by cBobeth** [comment]
Maybe `D_s^*` is the better option because there is also a `D_s` and maybe at some point also excited `D_s(XYZ GeV)` etc. Putting the spectator quark `P_q` on the pseudo-scalar meson first might also easier to generate strings automatically whenever there is an option for the flavour of the spectator quark, although this must be done anyway individually for each observable.

**Comment by gubernari** [comment]
Thanks Christoph for your feedback. I will change the name scheme as you
suggested, integrating the changes in my branch issue157.
Cheers,
Nico

**Comment by dvandyk** [comment]
The changeset has been merged now.
