### ISSUE TITLE
Relative path for environment variables 

### ISSUE THREAD

**Issue by Bilokin** [eos/eos#199]
Hello,

This is a remainder to correct the problem in Belle2 analysis environment, connected to the EOS_TESTS_PARAMETERS variable.

**Comment by dvandyk** [comment]
The underlying problem was that EOS searches for all datafiles under ```EOS_DATADIR```, which is set when running configure. We can overwrite this at runtime if you want. There is such a mechanism already, to be able to run the test cases. However, that is slightly different. I'll suggest a mechanism that @daritter can review.

**Comment by dvandyk** [comment]
Ahh, we have ```EOS_HOME```, which is exactly what you want I think. @daritter Can you try setting
```
export EOS_HOME=${prefix}/share
```
when installing basf2 into a non-standard location?

**Comment by dvandyk** [comment]
@Bilokin @daritter Having another look, it shoud be:
```
export EOS_HOME=${prefix}/share/eos
```
where ```${prefix}``` is the basf2 installation prefix.

@Bilokin Can you try that out?

**Comment by Bilokin** [comment]
Yes, this works! Thanks!

**Comment by daritter** [comment]
@Bilokin can you create a Bellle 2 issue for the externals so that I remember addind this setting?

**Comment by Bilokin** [comment]
@daritter, Sure!
