### ISSUE TITLE
Convert B->Kll to use an intermediate Amplitudes results

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#207]
@cBobeth Discussing right now with Mark Whitehead. From a look at the existing B->Kll code,
you and probably Christian Wacker had introduced the 6 functions ```F_A``` to ```F_T5```.
On the way to make this code agnostic of the final state hadron, I would like to move these
into a common ```Amplitudes``` struct. Any objections?

**Comment by dvandyk** [comment]
@cBobeth please have a look at dvandyk/eos, branch issue207

**Comment by cBobeth** [comment]
I had a look, but it seems you did not yet outsource all the code from "exclusive-b-to-s-dilaepton-low-recoil.cc" to "exclusive-b-to-s-dilepton.hh" concerning the calculation of the "amplitude-like" F_V,A,S,P,T,T5. Of course this calculation depends on large and low recoil, or more generally on the method chosen for the calculation of the amplitudes. This part should be probably templated and separated from the calculation of the observables. Then it will be also possible to generalize the B -> K and B -> pi into a B -> psd FCNC (rare) decay.

Maybe this is the easiest way to do it: derive completely new B->psd FCNC class (a la B->psd l v) from existing "exclusive-b-to-s-dilepton...", where the observables are given in terms of the amplitudes F_V,A,S,P,T,T5, which themselves are templated according to the method used to calculate them: QCDF, low-recoil OPE, parametrisation of cc-bar contribution etc. 

Sorry, maybe I just missunderstood, and your current efforts are all about this - since we had this idea already for quite some time.

**Comment by cBobeth** [comment]
Suggestion: Split `exclusive-b-to-s-dilepton.hh` into something like
-  `exclusive-B-to-Vector-dilepton.hh` 
- `exclusive-B-to-PsdScalar-dilepton.hh`

**Comment by dvandyk** [comment]
> Suggestion: Split `exclusive-b-to-s-dilepton.hh` into something like
> 
> * `exclusive-B-to-Vector-dilepton.hh`
> * `exclusive-B-to-PsdScalar-dilepton.hh`

Will do that right now. And in did, this was meant to be the first commit along the way to unify the code for low recoil and large recoil.

**Comment by dvandyk** [comment]
@mreboud I think this issue can be closed, correct?

**Comment by mreboud** [comment]
Yes :) I still need to convert part of it to use cacheable observable, but this is unrelated to this issue :)
