### ISSUE TITLE
Incompatibility to HDF5 1.10

### ISSUE THREAD

**Issue by sbrass** [eos/eos#23]
> HDF5-DIAG: Error detected in HDF5 (1.10.0) thread 0:
>   #000: H5Tarray.c line 117 in H5Tarray_create2(): not an valid base datatype
>     major: Invalid arguments to routine
>     minor: Inappropriate type

> HDF5-DIAG: Error detected in HDF5 (1.10.0) thread 0:
>   #000: H5F.c line 678 in H5Fflush(): not a file or file object
>     major: Invalid arguments to routine
>     minor: Inappropriate type
> terminate called after throwing an instance of 'eos::HDF5Error'
>   what():  H5Fflush failed and returned -1

[Compatibility Report](https://www.hdfgroup.org/HDF5/doc/ADGuide/Compatibility_Report/CR_1.10.0.html)

**Comment by dvandyk** [comment]
Simon, please give me some context in which this error occurred (e.g. make check, or running
a script).

**Comment by sbrass** [comment]
I've used a script which calls for eos-scan-mc with following options:

> --debug --seed '' --prerun-only --prerun-chains-per-partition 1 --prerun-update 400 --prerun-min 3000 --prerun-max 100000 --global-option form-factors KMPW2010 

and a lengthy constraints expression.
The error does not occur with HDF 1.18.16 - prelatest version.

**Comment by dvandyk** [comment]
I managed to reproduce this error. It occurs when an instance of
hdf5::Array<>, specifically hdf::Array<double, rank_>, is created.
The return value of hdf5::DataType<T_>::type_id() appears OK (56 to be specific).
I need to create a minimal EOS-independent test case, since

a. I might be using HDF5 in a wrong way, or
b. HDF5-1.10 might be buggy.

**Comment by dvandyk** [comment]
A little update: The following program minimal test case works:
```
int main(int, char **)
{
    char name[100];

    H5open();

    // obtain the HDF5 type id for double, little endian
    hid_t type_id_double = H5T_IEEE_F64LE_g;

    std::cout << "type_id_double = " << type_id_double << std::endl;
    printf("type_id_double = %li\n", type_id_double);

    // check if we would raise the HDF5-1.10.0 error:
    if (NULL == H5I_object_verify(type_id_double, H5I_DATATYPE))
        std::cout << "type_id_double is not a valid base datatype" << std::endl;

    // H5close();

    /*
     * create an HDF5 type for arrays of doubles, for rank=1
     * dimensions, with size=10 elements.
     */
    static const hsize_t rank = 1u;
    static const hsize_t size = 10u;
    const hid_t type_id_array = H5Tarray_create2(type_id_double, rank, &size);
    std::cout << "type_id_array = " << type_id_array << std::endl;

    return 0;
}
```
As soon as the `H5close()` call is uncommented, it fails with the same error as hdf5_TEST.
Looking into the original error, as well as the HDF5 source code, it appears that the memory
for the H5T_IEEE_F64LE is not yet initialized (no prior `H5open()` call) when `H5Tarray_create2()`
is called. However, this should be the case, since evaluation of the macro does call `H5open()'.
Really strange.

**Comment by dvandyk** [comment]
The definition of `hid_t` has changed from `int` (in HDF-1.8.x) to `int64_t` (in HDF-1.10.x).
Also, when printf-ing the base id from within `H5Tarray_create2()`, I obtained `56` for `H5T_IEEE_F64LE`, while my above minimal test case yields `216172782113783864`,
which turns out to be `3 << 56` + `56`. Casting the 64bit integer to 32bit would cut off the `3<<56` part.

Hypothesis: When mixing HDF-1.8 and HDF-1.10 headers and libraries, in either building EOS or building HDF5, the reported error occurs.

**Comment by dvandyk** [comment]
Ok, this looks promising:
```
sizeof(hid_t) = 4
```
from within EOS. This is wrong!
