### ISSUE TITLE
A possible mistake in the B->Plnu NP observables

### ISSUE THREAD

**Issue by DomLeljak** [eos/eos#275]
In `eos/b-decays/b-to-psd-l-nu.cc` line 304 (in the definition of `numerator_differential_a_fb_leptonic`) says:

- `std::abs(amp.h_0) * std::abs(amp.h_tS) * (1.0 - amp.v)`.

A comment states this is derived from `[DDS:2014A]`, eq. (12), and this term should come from the linear cos(theta) term in the first line of eq. (12). However, according to `[DDS:2014A]`, eq. (12), _if the entire (H_0 cos(theta) - H_tS) term is under absolute value_, line 304 should say something like:

- `std::real(amp.h_0 * std::conj(amp.h_tS)) * (1.0 - amp.v)`.

The two expressions are the same if the Wilson coefficients are real, but I think line 304 is wrong currently if they are considered complex. The final expression can/should be cross checked with `[STTW:2013A]`, eq. (53a). @dvandyk please check...

**Comment by dvandyk** [comment]
@DomLeljak thanks for this, I concur that this seems incorrect. ``git blame`` names me for this line, since I merged the B->Dlnu and B->pilnu codes. However, this bug was already in the B->Dlnu code before that. I think I can trace it back to @akokulu7's commit 7bb8aab8.

@cBobeth: @DomLeljak's solution seems correct. Do you concur?

**Comment by dvandyk** [comment]
Dom, please go ahead with the fix!

**Comment by akokulu7** [comment]
dear all (@dvandyk, @cBobeth , @DomLeljak ), 
concerning this issue I have received a mention email yesterday from github/eos and today I have found some time to crosscheck this issue (#275) for you, based on my past notes/programs. I have found my related mathematica program and now numerically crosschecked your point related to A_FB^leptonic  in   DDS:2014A versus STTW:2013A. (of course with complex WCs).
I confirm that the term in eq. (12) from [DDS:2014A], (H0 * cos(theta) - HtS)^2  is wrongly typed in this paper and should be understood as |H0 * cos(theta) - HtS|^2    instead of  (|H0| * cos(theta) - |HtS|)^2, as Dom pointed out. It is true that the discrepancy would only be noticeable when there are complex couplings.
So I concur this fix too! Thanks @DomLeljak  for pointing this out.
cheers, ahmet
