### ISSUE TITLE
Use gsl random generator

### ISSUE THREAD

**Issue by mreboud** [eos/eos#289]
This would also allow to solve issue #264 easily.

**Comment by dvandyk** [comment]
@mreboud Having looked at what type of random number distributions ``pypmc`` uses, I think it's best to stick to the following procedure:

 - keep the ``gsl_rng *`` until we have ripped out all of the sampling code from ``eos/statistics/``.
 - add three methods to the ``eos::LogPrior`` interface
    - ``evaluate(const double & x) const``
    - ``linear_evaluate(const double & x) const``
    - ``inverse_cdf(const double & p) const``
 - rewrite the existing ``LogPrior::sample`` to use ``inverse_cdf``. This works, since all priors are univariate.
 - write the ``sample`` method in Python, using a uniformly distributed variate and leverage ``inverse_cdf``.

**Comment by mreboud** [comment]
This issue can be closed now, right?

**Comment by dvandyk** [comment]
Indeed, fixed via #305
