### ISSUE TITLE
Varying CKM matrix elements in WilsonScan

### ISSUE THREAD

**Issue by DomLeljak** [eos/eos#313]
Currently, WilsonScan supports adding the Wolfenstein parameters to the likelihood, but not V_{CKM} (e.g. V_{ub} when considering $B\to \pi$). 

Is it a good idea to allow for varying simultaneously V_{CKM} elements and all Wilson coefficients?

@dvandyk suggested to open an issue to hear @mreboud 's and @cBobeth 's opinion.

**Comment by cBobeth** [comment]
As far as I understand, the intention of the model 'WilsonScan' was to fit the Wilson coefficients of the low-energy EFT (WET), i.e. performing model-independent analyses. In the WET framework the CKM parameters are not "fundamental" parameters, but only for historical reasons the CKM combinations have been factored out of the Wilson coefficients. The CKM parameters are fundamental parameters of the SM or it's extensions (some UV completion or SMEFT). Therefore the CKM parameters in the model 'WilsonScan' serve more as an overall scaling factor of the WET-Wilson coefficients that is fixed by hand  to some numerical value before the fit is done.

In the analysis on B -> D^* lv (arXiv:2104.02094) we have seen that this might be a limitation and that the possibility to use the CKM parameters as an overall scaling factor allows for some more flexible parametrization of WET Wilson coefficients. But the user must really understand that he is not really fitting CKM parameters. For the moment I would rather avoid to keep this kind of possibilities of misusing CKM parameters in 'WilsonScan.

There is also the model 'CKMScan', which is more or less SM with CKM parameters to be fitted, which should be used in this case.

**Comment by cBobeth** [comment]
By the way: the same holds for the overall factor `G_F', i.e. the Fermi constant, which is also by convention pulled out as a factor ...

**Comment by dvandyk** [comment]
> But the user must really understand that he is not really fitting CKM parameters.

I agree with Christoph here.

> For the moment I would rather avoid to keep this kind of possibilities of misusing CKM parameters in 'WilsonScan'.

However, not being able to set CKM matrix elements directly in the WilsonScan approach is a genuine problem.

> There is also the model 'CKMScan', which is more or less SM with CKM parameters to be fitted, which should be used in this case.

Sorry, no Christoph. Dom's approach is the same as ours in the paper with Nico, Marzia and Martin: Fit Wilson coefficients while keeping some normalization.


I would suggest to swap ``SMComponent<CKM>`` with ``CKMScanComponent`` in the definition of ``WilsonScanModel``.

Avoiding that users simultaneously fit ``CKM::V_ub`` and ``b->ulnu::Re{C_VL}`` is a genuine possibility. But not somthing that we can effectively avoid.

**Comment by cBobeth** [comment]
Setting CKM parameters to some fixed value is one thing. 

What I had in mind, was to fit the CKM parameters along with Wilson coefficients, because it would be a parametrization with ambiguities. Moreover CKM parameters can not be interpreted as CKM parameters in this context, just as some overall numerical normalization factor.

**Comment by dvandyk** [comment]
I completely agree, but that's exactly the purpose here! Dom wrote 'varying', not 'fitting'.

**Comment by cBobeth** [comment]
Dom wrote "varying simultaneously CKM  and Wilson coefficients", so for me it sounded like fitting both?!

I thought that one can always change default values of all parameters to whatever value, independently of the limited set of  parameters that can be fitted in a model.

**Comment by DomLeljak** [comment]
What I would like to do is set `CKM::abs(V_ub)` to a certain value as a normalization factor, and fit to Wilson coefficients, I'm sorry for not being clear. Currently, setting `CKM::abs(V_ub)` to any value has no effect on the outcome of the fit.

**Comment by cBobeth** [comment]
Dom, to be sure, please look in the source code and see where the CKM parameters are taken from in the model you are using. 

Maybe you have to use these parameters to set CKM elements:

["CKM::lambda"], ["CKM::A"], ["CKM::rhobar"], ["CKM::etabar"]

in the model "WilsonScan". At least this is what I did for our work on B->D* lv.
