### ISSUE TITLE
Provide means to check if EOS/eoshep has been correctly installed

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#323]
Flavio Archilli reported that the ``eos`` package installs an ``eos`` module.

**Comment by dvandyk** [comment]
And this is why I hate python. ``setuptools`` does not provide any means to provide conflict information.

**Comment by pluegh** [comment]
You can check your installation in the console with `python3 -c "import eos; help(eos)"`, which shows authors and a package description.

This works on linux with a pip installation.
I propose to update the pip installation section with the clause that the module can be checked this way if there are any problems, as a first response. This diagnoses not only if, but which eos is imported by the python interpreter.

I suppose the _proper_ way of handling this problem is by wrapping an `eos` module into the `eoshep` package, such that the import is `from eoshep import eos`... but I'm not so familiar with distribution.

**Comment by dvandyk** [comment]
@pluegh Can you write that up briefly and succinctly and add it to the FAQ?

**Comment by dvandyk** [comment]
Philip's commit modifying the installation documentation has been merged. Closing.
