### ISSUE TITLE
Refactoring the use of examples in the documentation

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#347]
- Philip thinks we should use raw HTML tables in the doc when representing Jupyter notebook outputs.
   - Stephan mentioned that some Jupyter outputs are not possible with the ``list-table`` RST directive.
   - Philip mentioned that Jupyter supports exporting notebooks to RST.

We should sync the notebook tables to the documentation. Low-priority issue.

**Comment by mreboud** [comment]
I think it is time to solve this issue. Here is what I suggest:
 - Notebooks should be pushed to Git only w/o content so that we can trace changes
 - [nbsphinx](https://nbsphinx.readthedocs.io/) allows to use the notebook directly in the documentation instead of the rst files that we currently have to copy. It is smart enough (1) to run the entire notebook before using it and (2) to handle links correctly (I still need to check that)
