### ISSUE TITLE
A bug (?) concerning uppercase Option Values (and maybe Keys)

### ISSUE THREAD

**Issue by DomLeljak** [eos/eos#374]
Running an analysis that uses `b-to-vec-l-nu.cc` I notice that providing an unallowed value for `SwitchOption` defined with a key `'U'` doesn't yield an error message according to the line 115 of `options-impl.hh` (which happens correctly if I provide an unallowed value for options with the key `'l'`or `'q'`). This is fixed by defining the key with a lowercase.

This is weird because the allowed option keys in line 106 of `qualified-name.cc` seem to be both lowercase and uppercase letters (even though it says right above it that only lowercase letters are allowed in a comment). If I provide a symbol not provided in line 106 of `qualified-name.cc` the error is correctly diplayed.

Can someone confirm that providing an unallowed value to the option with the key 'U' doesn't yield an error message, and that this is fixed by using lowercase letters as option keys?

**Comment by mreboud** [comment]
I can reproduce the error for b-to-d-l-nu (see branch issue374). What puzzles me for the moment is that implementing an equivalent incorrect switch option in options_TEST.cc did not rise any issue...

**Comment by mreboud** [comment]
After a discussion with @dvandyk, we understood that there are no issue here a priori :)

You are probably using an observable such as `B->Dlnu`, where the `U` option is forced to a given value (`c` in this case see https://github.com/eos/eos/blob/ce65b8746149739f81f75939d797c8d0e56aa00f/eos/b-decays/observables.cc#L194). So when you change the value of `U`, nothing happens because it is overwritten by the `U` option of the observable. This has nothing to do with upper- vs. lowercase: `l` or `q` are indeed options that you can modify.

@dvandyk is working on a commit to warn the user that an option was overwritten.

If you agree on all of this, can you close the issue?

**Comment by DomLeljak** [comment]
Thank you, all is clear now. The options in the analysis get overwritten by the options provided by the observable.

Closing.
