### ISSUE TITLE
sample_pmc has a couple of weaknesses

### ISSUE THREAD

**Issue by mreboud** [eos/eos#462]
1. The treatment of weights is inconsistent https://github.com/eos/eos/blob/f6615b6017d323fbc2f6b3050b9feca744daffa2/python/eos/analysis.py#L463-L465 because some weights are smaller than `eps = np.finfo(float).eps`. Maybe we should change the definition of `eps` or use the minimal weight as a minimum value.
2. As noted by @dvandyk we are currently updating the PMC using all the generated samples, which is ok. But using their outdated weights which is definitely wrong.
3. The update of the PMC may be run several times on the same sample step, this iterative process may improve the convergence

**Comment by dvandyk** [comment]
From the discussion at today's meeting:

1. Try to get rid of adjusted weights, since ``self._perplexity`` already masks negative weights.
    If this does not work, use ``eps`` even for samples with ``weight = 0``.
    
2. Use ``pypmc.sampler.importance_sampling.combine_weights`` on the samples from the last ``pmc_lookback + 1`` update steps. Default ``pmc_lookback = 0``.

3. Yes, using default of ``pmc_iterrations = 1``.
