### ISSUE TITLE
option `'scaling_factor'` is broken in the `Plotter`

### ISSUE THREAD

**Issue by mreboud** [eos/eos#577]
Probably due to yet another matplotlib version, the option `'scaling_factor'` is not working...

Here is a workaround:
```python
import matplotlib.ticker as ticker

plot = eos.plot.Plotter(plot_args, "my_fig.pdf")
plot.setup_plot()

scale_x = 1e-2
ticks_x = ticker.FuncFormatter(lambda x, pos: '{0:g}'.format(x/scale_x))
plot.ax.get_xaxis().set_major_formatter(ticks_x)

plot.plot_contents()
plt.tight_layout()
plt.savefig(plot.output, bbox_inches='tight', dpi=300)
```

**Comment by dvandyk** [comment]
Ok, I could trace the bug a bit further. It seems that the axis' major formatter is overwritten after we set it.
Printing it prior to setting it shows the default to be a ``ScalarFormatter``, and not a ``FuncFormatter``.
After calling ``set_major_formatter`` the type changes. After ``setup_plot`` returns, the type has reverted to ``ScalarFormatter``.

**Comment by dvandyk** [comment]
I suspect the call to ``self.ax.set`` reverts the formatter:
https://github.com/eos/eos/blob/9441b7beadca98b5a22e6b4c6ecfdc9d19621c44/python/eos/plot/plotter.py#L200

**Comment by SKuerten** [comment]
As described above
https://github.com/eos/eos/blob/9441b7beadca98b5a22e6b4c6ecfdc9d19621c44/python/eos/plot/plotter.py#L200
breaks the `scaling_factor` option. Commenting out line 200 makes the `scaling_factor` option work again.
splitting line 200 like this:
`self.ax.set_xlabel(myxlabel)`
`self.ax.set_xscale(myxscale)`
`self.ax.set_ylabel(myylabel)`
`self.ax.set_yscale(myyscale)`
`self.ax.set_title(mytitle)`
and checking which of these lines break (checking = scaling a plot in example notebooks, commenting out one of the lines and reinstalling eos, repeat that for different combinations) the `scaling_factor` option it turns out that 
`self.ax.set_xscale(myxscale)`
`self.ax.set_yscale(myyscale)`
break the `scaling_factor` option independent of one another (e.g. if you only add `self.ax.set_xscale(myxscale)` the scaling in the y-axis still works as intended)

At the moment I don't know how to fix this.
This behaviour is - to my knowledge - not document in [https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set.html](url) or either of the specific axes settings.
