### ISSUE TITLE
Handle GSL error gracefully

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#64]
Presently EOS exits with ```abort()``` when the GSL error handler is invoked. We should find a way to change that.

**Comment by fredRos** [comment]
What could you prefer? Throw an exception like this

```c++
class GSLError :
        public Exception
```

Or should it not inherit from Exception?

**Comment by dvandyk** [comment]
Inheriting from ```Exception``` is perfectly fine.

**Comment by fredRos** [comment]
The [gsl docs](https://www.gnu.org/software/gsl/doc/html/err.html) explain this well. We have a number of places in the code where we turn of the default error handler. Look for 
```c++
gsl_error_handler_t * default_gsl_error_handler = gsl_set_error_handler_off();
```
We could set a custom handler globally, for example with a static variable during initialization of the library. But I see a problem with multiple threads because the error handling is defined globally within GSL. For example, if some thread explicitly checks errors, it turns off the handler. A concurrently executing thread relies on the error handler throwing exceptions but no exception can be thrown. 

For our applications, it seems that the error handler is deactivated only during ctors or initialization routines so we may get away with it w/o thread race conditions.

**Comment by dvandyk** [comment]
The GSL documentation recommends to switch off the default error handler or to replace it with a custom one.

Coming back to this issue, my plan is now to:
 - [ ] audit the code to make sure the return values of calls to ```gsl_*``` are inspected;
 - [ ] create a new exception class ```GSLError``` that can be thrown in such cases in which we cannot continue running;
 - [ ] disable the GSL error handler within a free-standing function with ```__attribute__((constructor))```, to be included in ```libeos.so```.

**Comment by mreboud** [comment]
@dvandyk by "inspected", do you mean (1) to ensure that the pointer exists and (2) that the gsl objects are properly unallocated?
