### ISSUE TITLE
Interpolation issue for `uncertainty` plotter

### ISSUE THREAD

**Issue by lorenzennio** [eos/eos#903]
There is an interpolation issue when plotting uncertainties in regions of high gradient. @mreboud mentioned Runge's phenomenon.

One (extreme) example plot:
![image](https://github.com/user-attachments/assets/1f070f5f-3bc5-4ef8-aca7-d5fed5b99c91)

where the actual points are:
![image](https://github.com/user-attachments/assets/99943239-cad7-4b42-9f86-6d8cc9463075)

Potential solutions could be to disable continuous plotting in the `uncertainty` plotter or to warn the user about this.

**Comment by mreboud** [comment]
I think this is not a problem we should fix on the EOS side. What we can do is:

1. Add a comment, maybe in the FAQ, saying that this is due to Runge's phenomenon and perhaps a couple of suggestions to eliminate the oscillations (reducing the number of points, using Chebyshev-compatible points, ...).
2. Add an option to turn the spline interpolation off

@dvandyk, any thoughts?
I am slightly surprised that such oscillations appear with CubicSplines though...

**Comment by MJKirk** [comment]
My vote would be to simply replace the CubicSpline interpolation with a linear interpolation (or offer both, but defaulting to linear), and also offer an option to show the points being plotted on top. 
Then if the curve isn't smooth enough, the user has to produce more data points, rather than us trying to magic up a smooth curve out of potentially not smooth data.

**Comment by mreboud** [comment]
> My vote would be to simply replace the CubicSpline interpolation with a linear interpolation (or offer both, but defaulting to linear), and also offer an option to show the points being plotted on top. Then if the curve isn't smooth enough, the user has to produce more data points, rather than us trying to magic up a smooth curve out of potentially not smooth data.

I like this suggestion.

**Comment by Herren** [comment]
> My vote would be to simply replace the CubicSpline interpolation with a linear interpolation (or offer both, but defaulting to linear), and also offer an option to show the points being plotted on top. Then if the curve isn't smooth enough, the user has to produce more data points, rather than us trying to magic up a smooth curve out of potentially not smooth data.

I fully agree, having both options available would be great!
